### ISSUE TITLE
pack Indefinitely adds transitive module

### ISSUE THREAD

**Issue by monicadeshmukh** [go-sharp/go-offline-packager#6]
I am trying to use the offline packager to pack my project for offline use. I tried using go version 1.20 and 1.21. When I use the command  go-offline-packager.exe pack -t -v -g go.mod, it runs indefinitely 
Packaging: adding transitive module: go@1.20
Packaging: adding transitive module: go@1.20
Packaging: adding transitive module: go@1.20
Packaging: adding transitive module: go@1.20
Packaging: adding transitive module: go@1.20

go.mod file

module modulename

go 1.20

require (
	github.com/fatih/color v1.16.0
	github.com/spf13/cobra v1.8.0
)

require (
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/pkg/errors v0.9.1
	github.com/rs/zerolog v1.32.0
	github.com/spf13/pflag v1.0.5 // indirect
	golang.org/x/sys v0.14.0 // indirect
)

when I tried with go 1.21, the command ran indefinitely when packaging toolchain module.
Packaging: adding transitive module: toolchain@go1.21.7
Packaging: adding transitive module: go@1.21.7
Packaging: adding transitive module: toolchain@go1.21.7
Packaging: adding transitive module: go@1.21.7
Packaging: adding transitive module: toolchain@go1.21.7
Packaging: adding transitive module: go@1.21.7
Packaging: adding transitive module: toolchain@go1.21.7

Tried the pack command with another go.mod file and it has the same issue.

Thank you for your help.

**Comment by snmed** [comment]
Thank you for reporting this issue. I will look into it as soon as I can spare some free time.

**Comment by snmed** [comment]
Should be fixed with latest version v0.1.4
